services:
  api:
    container_name: nest_dev
    build:
      context: ../..
      dockerfile: docker/dev/Dockerfile
    develop:
      watch:
        - path: ./src
          action: sync
          target: /app/src
        - path: ./package.json
          action: rebuild
    env_file:
      - .env.development
    ports:
      - "3000:3000"
      - "51212:51212" # For prisma studio
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres_dev
    restart: always
    env_file:
      - .env.development
    ports:
      - "5433:5432"
    volumes:
      - npb_dev_data:/var/lib/postgresql/data

volumes:
  npb_dev_data:
